var GAME_LEVELS = [
 ["x                                                          x",
  "x                                                          x",
  "x                                                          x",
  "x   xx                   xxx               xxx             x",
  "x    x                      x                 x            x",
  "x    x                    xx               xxx             x",
  "x    x                   x                    x            x",
  "x   xxx                  xxx               xxx             x",
  "x                                                          x",
  "x                                                          x",
  "x                                                          x",
  "x                   @                                      x",
  "xxxxxx1xxxxxxxxxxxxxxxxxxx2xxxxxxxxxxxxxxxxxx3xxxxxxxxxxxxxx",
  "     x x                 x x                x x             ",
  "     x x                 x x                x x             ",
  "      x                   x                  x              "], 

  [" y  o                                                                                                                                     ",
   "                                                                                                                x                         ",
   "                                                                                                                x                         ",
   "                                                                                                                x    xxxxxxx              ",
   "                                                                                     xxxxxxxxxxxx               x    x            xxxxxxx ",
   "                                                                                   xxx                          x    x                  x ",
   "                                                                                 xxx               xxxxxxxxxxxxxxx   x                  x ",
   "                                                                               xxx                                   x          xxxxx   x ",
   "                                                                             xxx                                     x              x   x ",
   "                                                                      xxxxxxxx             xxxxx                    xx              x   x ",
   "                                                                                                                                    x   x ",
   "                                                            x!!!!x                                            xxx                   x   x ",
   "         xx                                                 xxxxxx =            xxxx                   xxx                          x   x ",
   "         xx                  xxxxx        x!                                                                                        x   x ",
   "         xx                                        xxxxx                                   xx                                       x   x ",
   "         xx    @       xxxx              !x!                               xxxxx                     xx                             x   x ",
   "         xx                                                                                                                         x   x ",
   "         xxxxxxxxxxxxx      xxxxxxxxxxx       xxxxxxxxxxx            xxxxxxx      xxxxxx       xxxx                                 x   x ",
   "                                      x!!!!!!!x         x!!!!x!!!!x!!x                                                              x   x ",
   "                                      x!!!!!!!x         x!!!!!!!!!!!!x                                                              x   x ",
   "                                      x!!!!!!!x         x!!!!!!!!!!!!x                                                              x 1 x ",
   "                                      xxxxxxxxx         xxxxxxxxxxxxxx                                                              x   x ",
   "                                                                                                                                    x   x ",
   "                                                                                                                                    xxxxx "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "               1                                               xxx                                                ",
   "                                                               xxx                                                ",
   "                                                               xxx                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=   xxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxx",
   "x                   x                                         x                                                  x",
   "x                   x                                         x                                                  x",
   "xxxxxxxx   xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                    x                                                                           x",
   "x                                    x                                                                           x",
   "xxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx",
   "x        x                                                                      x                                x",
   "x        x                                                                      x                                x",
   "xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxx",
   "x                 x      =                     x                                         x                       x",
   "x                 x                         =  x                                         x                       x",
   "xxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = xxxx",
   "x                                                                     x                                          x",
   "x                                                                     x                                          x",
   "xxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx",
   "x                                                                                    x                           x",
   "x                                                                                    x                           x",
   "xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                     x               x                                          x",
   "x                                                     x               x                                          x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=   xxxxxxxxxxx =  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxx",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "x                                                  x              x                                         x    x",
   "x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxx xxx",
   "x                                              x            x                                                    x",
   "x                                              x         =  x                                                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxx xxxxxxx",
   "x                                                                                                      x         x",
   "x                                                                                                      x         x",
   "xxx   xxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxx xx",
   "x                    x =          x                                                 x                            x",
   "x                    x      =     x                                                 x                            x",
   "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxx  =  xxxxxxxxxxxxxxxxxxx  = xxxxxxxxxxxxxxxx=   xxxxxxx  = xxxxxx   xxxxxxxxxx",
   "x                                                                                                                x",
   "x@                                                                                                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " z                                                                                                                ",
   "                                                                                                                 o",
   "           x                                                                                                      "],
  ["           x                                                                                                 o",
   "           x                                                                                                ",
   "xxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                         c |           c     |       c          |  x                                        x",
   "x                                                                   x                                        x",
   "x                                                                                                        x   x",
   "x                x  x   xxx                                                                              x   x",
   "x                         xxx   xxxxxxxxxxxx  xxxxxx  xxxxxxxxxx  xxxxx                             xxxxxx   x",
   "x         x               x                    x                    x       =              =            =x   x",
   "x                         x                    x                    x               =            =       x   x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x",
   "x |              | c            |   c                                                                    x   x",
   "x                                                                                                        x   x",
   "x                                                                                                        x   x",
   "x                                                                                                        x   x",
   "x        xxx xxxxxxxxxxxxx xxxxxxxxxxxx                                                                  x   x",
   "x          x x           x x        x         x                                                          x   x",
   "x           x             x         x                                                                    x   x",
   "x                                   x               x                                                    x   x",
   "x                                   x                                                                    x   x",
   "x                                   x           x         x     =  x       =x        xxxxxx              x   x",
   "x                               1   x                                                                    x   x",  
   "x                                   x                             =                              xxxx        x",
   "x                                   x          =                                      =          c        @  x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
